name: Build IPK

on:
  push:
    branches:
      - main  # 触发条件，可以根据需要修改
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # 使用最新的 Ubuntu 环境

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 检出代码

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential  # 安装编译工具

      - name: Build IPK
        run: |
          cd luci/luci-app-qmodem-mwan  # 进入项目目录
          make  # 执行 make 命令

      - name: Upload IPK
        uses: actions/upload-artifact@v2
        with:
          name: qmodem-ipk
          path: luci/luci-app-qmodem-mwan/*.ipk  # 上传生成的 IPK 文件

