name: Build OpenWrt for x64 with mwan

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Prepare build environment
      uses: P3TERX/openwrt-action@main
      env:
        DEBIAN_FRONTEND: noninteractive

    - name: Download and prepare OpenWrt SDK
      run: |
        git clone https://github.com/openwrt/openwrt.git
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        echo "CONFIG_TARGET_x86=y" > .config
        echo "CONFIG_TARGET_x86_64=y" >> .config
        echo "CONFIG_TARGET_x86_64_generic=y" >> .config
        # Note: The package is likely named luci-app-mwan3
        echo "CONFIG_PACKAGE_luci-app-mwan3=y" >> .config
        make defconfig

    - name: Compile all packages AND luci-app-mwan3
      run: |
        cd openwrt
        make -j$(nproc)

    - name: Collect artifacts
      run: |
        mkdir -p artifacts
        find openwrt/bin/packages/x86_64/base -name "luci-app-mwan3*.ipk" -exec cp {} artifacts/ \;
        find openwrt/bin/targets/x86/64 -name "*.*" -exec cp {} artifacts/ \;

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: openwrt-x64-firmware-with-mwan3
        path: artifacts/
